## This analysis is centered around using a new reference panel with more SNPs
#	hopefully attenuating the increase in false positives that we have been 
#	observing in the previous analyses.
#
#	This is going hopefully towards publication eventually. 

# Set up some variables first.
hapgen2=
home=/scratch/hpc2862/CAMH/new_corge


# The default rule
# 	For now just update the git repo.
.all: git

# Git add rule
# 	
git:
	git add -A
	git commit -am "update coRge for new analysis see changelog" 


