---
title: "LD Thresholding"
author: "Christopher B. Cole"
date: "June 6, 2016"
output: html_document
---

All of the following uses `coRge v0.5.6.9000` as tagged [here](https://github.com/Chris1221/coR-ge/releases/tag/v0.5.6.9000), SHA commit `7148e9e`.

## Introduction

We take the list of generated causal SNPs ($h^2 = 0.45$, $n = 1000$) and use `plink 1.9` to find all SNPs within a 500kb region which have $R^2 > 0.2$ with any of the causal SNPs. We take the unique entries in this list and note $R^2$. We then sweep through all levels of LD `c(0, 0.2, 0.4, 0.6, 0.8, 0.9, 1)` and correct accordingly:

Correction function:

```{R, eval = F}
for(th in levels(as.factor(strata$ld))){

        message("Calculating sFDR and FDR")

        strata %>%
          filter(s == 1) %>%
          mutate(p.adj = p.adjust(P, method = "BH")) %>%
          fdr(., mode = "ld", level = th) ->
          s1

        strata %>%
          filter(s == 2) %>%
          mutate(p.adj = p.adjust(P, method = "BH")) %>%
          fdr(.,  mode = "ld", level = th) ->
          s2

        strata %>%
          mutate(p.adj = p.adjust(P, method = "BH")) %>%
          fdr(., mode = "ld", level = th) ->
          agg

        sfdr <- (s1[1]+s2[1]) / (s1[1]+s2[1] + s1[2]+s2[2])
        fdr <- agg[3]

        out[nrow(out)+1,] <- c(sfdr, fdr, "all", th)
  }
```

and `fdr()`:

```{R, eval = F}
else if(mode == "ld"){

		fp <- sum(!is.na(df$p.adj[(df$p.adj < 0.05 & !(df$h1)) | (df$p.adj < 0.05 & df$ld > level)]))
		tp <- sum(!is.na(df$p.adj[(df$p.adj < 0.05 & df$h1) | (df$p.adj < 0.05 & df$ld > level)]))
		fdr <- fp / (tp + fp)

	}

 	return(c(fp, tp, fdr))
```


## Results
#### Omnibus

After 30 runs (not all of which finished), we see the following: 

```{R, eval = T, echo = F, message = F}
library(data.table)
library(dplyr)
library(tidyr)
library(magrittr)
library(ggvis)
```

```{R}
ld <- fread("~/repos/coR-ge/data/test_run2.txt", h = T)
head(ld)
```

We reformat the data from wide to long:

```{R}
ld %<>% gather(key = "s", value = "fdr", sfdr, fdr)

ld$s <- as.factor(ld$s)
ld$k <- as.factor(ld$k)
ld$th <- as.factor(ld$th)

head(ld)

ld.na <- na.omit(ld)

ld.na %>% filter(s == "fdr") %>% ggvis(~th, ~fdr) %>% layer_boxplots() %>% add_axis("x", title="fdr")

ld.na %>% filter(s == "sfdr") %>% ggvis(~th, ~fdr) %>% layer_boxplots() %>% add_axis("x", title="sfdr")
```

And perform a regression to examine the differences:

```{R}
ld %>% lm(fdr ~ s + k + th, .) %>% summary
```

We can see that stratefied / non stratefied only leads to a small 0.5% decrease in FDR. 

#### Pairwise

Despite the fact that as a whole the differences were not significant, in some subsets, the differences are much more pronounced, leading to a difference of between 2 and 3% reduction in FDR. With increased number of trials, this will probably become significant.

```{R}
ld %>% filter(k == 3) %>% filter(th == 0.4) %>% t.test(fdr ~ s, data = .)
```

In general, I think that we have too low power to reliably see the difference between FDR and sFDR. Either that, or the 50/50 split is not enough to actually prioritize the results and see a difference.

This is $n = 5000, h^2 = 0.45$, split = 50 50 causal, 50 50 non-causal.

